{
 "title": "守护进程集应用监控",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_daemonset_created, namespace)"
    }
   },
   {
    "name": "daemonset",
    "label": "daemonset",
    "query": {
     "query": "label_values(kube_daemonset_created{namespace=~\"$namespace\"},daemonset)"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~'$namespace',pod=~\"$daemonset.*\"} ,pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{pod=~'$Pod'} ,container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "statefulset",
   "type": "text",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "options": {
    "content": "\n# $container\n\nMore Info : [ARMS](https://arms.console.aliyun.com/)\n\n\n\n"
   },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod_name=~\"$Pod\",namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "Pod Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(sum(container_memory_working_set_bytes{pod=~\"$Pod\",namespace=\"$namespace\"}) by(pod))"
    }
   ]
  },
  {
   "title": "spec_replicas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(kube_daemonset_status_desired_number_scheduled{daemonset=\"$daemonset\"})"
    }
   ]
  },
  {
   "title": "Pod Mem Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",pod=~\"$Pod\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pod memory limit",
   "type": "stat",
   "description": "没有配额的情况下默认值是0",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (container_spec_memory_limit_bytes{image!=\"\",pod=~\"$Pod\",namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pod CPU Usage Secs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",pod=~\"$Pod\",namespace=\"$namespace\"}[1m]))"
    }
   ]
  },
  {
   "title": "restarts_total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (  (kube_pod_container_status_restarts_total{ pod=~\"$Pod\",namespace=\"$namespace\"} ))"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",pod=~\"$Pod\",namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{ pod_name }}"
    },
    {
     "expr": "max (kube_pod_container_resource_limits_memory_bytes{pod=~\"$Pod\",namespace=\"$namespace\"})>0",
     "legendFormat": "limit"
    },
    {
     "expr": "max (kube_pod_container_resource_requests_memory_bytes{pod=~\"$Pod\",namespace=\"$namespace\"})>0",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Pods CPU usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",pod=~\"$Pod\",namespace=\"$namespace\"}[1m])) by (pod)",
     "legendFormat": "{{ pod_name }}"
    },
    {
     "expr": "max (kube_pod_container_resource_limits_cpu_cores{pod=~\"$Pod\",namespace=\"$namespace\"})>0",
     "legendFormat": "limit"
    },
    {
     "expr": "max (kube_pod_container_resource_requests_cpu_cores{pod=~\"$Pod\",namespace=\"$namespace\"})>0",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",pod=~\"$Pod\",namespace=\"$namespace\"}[1m])) by (pod)",
     "legendFormat": "Received {{pod_name}}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",pod=~\"$Pod\",namespace=\"$namespace\"}[1m])) by (pod)",
     "legendFormat": "Sent {{pod_name}}"
    }
   ]
  },
  {
   "title": "fs writes/reads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "- sum(rate (container_fs_writes_bytes_total{image!=\"\",pod=~\"$Pod\",namespace=\"$namespace\"}[1m])) by (pod) ",
     "legendFormat": "write {{pod_name}}"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{image!=\"\",pod=~\"$Pod\",namespace=\"$namespace\"}[1m])) by (pod) ",
     "legendFormat": "read {{pod_name}}"
    }
   ]
  }
 ]
}