{
 "title": "Pod性能Top监控",
 "tags": [
  "kubernetes",
  "pod"
 ],
 "time": { "from": "now-3m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Pod Top 5 Memory/GB",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(5,sum (container_memory_working_set_bytes{image!=\"\"}) by (instance,namespace,pod_name))/1024/1024/1024",
     "legendFormat": "{{instance}}/{{ namespace }}/{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pod Top 5 CPU/core",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk(5,sum (rate (container_cpu_usage_seconds_total{image!=\"\"}[1m])) by (instance,namespace,pod_name))",
     "legendFormat": "{{instance}}/{{ namespace }}/{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pod Top 5 net/in",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "topk(5,sum (rate (container_network_receive_bytes_total{image!=\"\"}[1m])*8) by (namespace,pod_name,instance))",
     "legendFormat": "{{instance}}/{{ namespace }}/{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pod Top 5 net/out",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "topk(5,sum (rate (container_network_transmit_bytes_total{image!=\"\"}[1m])*8) by (instance,namespace,pod_name))",
     "legendFormat": "{{instance}}/{{ namespace }}/{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pod Top 5 filesystem",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "topk(5,sum (container_fs_usage_bytes) by (instance,job,device))",
     "legendFormat": "{{instance}}/{{ job }}/{{ device }}"
    }
   ]
  },
  {
   "title": "Pod fail",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Failed\"}) by(namespace,pod_name)==1",
     "legendFormat": "{{ namespace }}/{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pod terminated",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_terminated{}) by (namespace, pod_name) ==1",
     "legendFormat": "{{ namespace }}/{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pod restart",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{}[15m])) by (namespace,pod_name) >0",
     "legendFormat": "{{ namespace }}/{{ pod_name }}"
    }
   ]
  }
 ]
}