{
 "title": "Pod监控",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "kubeDatasource", "query": "aliyun-kubernetes-datasource" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_created, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_created{namespace=\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Namespace",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_namespace_labels{namespace=\"$namespace\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Age",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(kube_pod_created{pod=~\"$pod\",namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_status_ready{namespace=\"$namespace\", pod=~\"$pod\", condition=\"true\"}) or on() vector(0)",
     "legendFormat": "Ready"
    }
   ]
  },
  {
   "title": "Phase",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_pod_status_phase{namespace=~\"$namespace\", pod=~\"$pod\"}==1) by (phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "table",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "group by (image, container,pod) (kube_pod_container_info{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (container,pod)(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "Restarts"
    },
    {
     "expr": "sum by (container,pod)(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "CPU Request"
    },
    {
     "expr": "sum by (container,pod)(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "Memory Request"
    },
    {
     "expr": "max by (container,pod)(kube_pod_container_status_running{namespace=\"$namespace\", pod=~\"$pod\"})"
    },
    {
     "expr": "sum by (container,pod)(kube_pod_container_resource_limits{resource=\"cpu\",namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "CPU Limit"
    },
    {
     "expr": "sum by (container,pod)(kube_pod_container_resource_limits{resource=\"memory\",namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "Memory Limit"
    }
   ]
  },
  {
   "title": "Node Name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_info{pod=~\"$pod\",namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Restart Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum (increase(kube_pod_container_status_restarts_total{pod=~\"$pod\",namespace=\"$namespace\"}[1h])))",
     "legendFormat": "Last 1 Hour"
    },
    {
     "expr": "sum(max(kube_pod_container_status_restarts_total{pod=~\"$pod\",namespace=\"$namespace\"})by (pod))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", pod=~\"$pod\"}) or vector(0)",
     "legendFormat": "CPU (cores)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", pod=~\"$pod\"}) or vector(0)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Limits",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", pod=~\"$pod\"}) or vector(0)",
     "legendFormat": "CPU (cores)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", pod=~\"$pod\"}) or vector(0)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Warning Events",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 5 },
   "targets": [
    {
     "expr": "ceil(increase(eventer_events_error_total{namespace=\"$namespace\", name=\"$pod\", kind=\"Pod\"}[1m]))>0 or ceil(increase(eventer_events_warning_total{namespace=\"$namespace\", name=\"$pod\", kind=\"Pod\"}[1m]))>0",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  { "title": "Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory/Limit (%)",
   "type": "timeseries",
   "description": "提供了 RSS, Usage, WorkingSet 三种维度的内存使用量相对于限制量的比例。通常以 WorkingSet 作为最关键的参考。 ",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(max(container_memory_rss{pod=~\"$pod\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (pod,namespace,container)/ sum(container_spec_memory_limit_bytes{pod=~\"$pod\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (pod,namespace, container) * 100) <= 100 or on() vector(0)",
     "legendFormat": "{{pod}}/{{container}}(RSS/Limit)"
    },
    {
     "expr": "(max(container_memory_usage_bytes{pod=~\"$pod\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (pod,namespace,container)/ sum(container_spec_memory_limit_bytes{pod=~\"$pod\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (pod,namespace, container) * 100) <= 100 or on() vector(0)",
     "legendFormat": "{{pod}}/{{container}}(Usage/Limit)"
    },
    {
     "expr": "(max(container_memory_working_set_bytes{pod=~\"$pod\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (pod,namespace,container)/ max(container_spec_memory_limit_bytes{pod=~\"$pod\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (pod,namespace, container) * 100) <= 100 or on() vector(0)",
     "legendFormat": "{{pod}}/{{container}}(WSS/Limit)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_memory_rss{pod=~\"$pod\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (pod,namespace,container) or on() vector(0)",
     "legendFormat": "{{pod}}/{{container}}(RSS)"
    },
    {
     "expr": "max(container_memory_usage_bytes{pod=~\"$pod\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (pod,namespace,container)",
     "legendFormat": "{{pod}}/{{container}}(Usage)"
    },
    {
     "expr": "max(container_memory_working_set_bytes{pod=~\"$pod\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (pod,namespace,container)",
     "legendFormat": "{{pod}}/{{container}}(WSS)"
    }
   ]
  },
  {
   "title": "Memory Failcnt",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max (increase(container_memory_failcnt{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\"}[1m])) by (pod,container)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Network Error(Percent)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max (increase (container_network_receive_packets_dropped_total{id!=\"/\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (pod,interface) / max (increase (container_network_receive_packets_total{id!=\"/\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (pod,interface)",
     "legendFormat": "{{pod}}/{{interface}}(DroppedPacket-Input)"
    },
    {
     "expr": "max (increase (container_network_transmit_packets_dropped_total{id!=\"/\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (pod,interface) / max (increase (container_network_transmit_packets_total{id!=\"/\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (pod,interface)",
     "legendFormat": "{{pod}}/{{interface}}(DroppedPacket-Output)"
    },
    {
     "expr": "max (increase (container_network_receive_errors_total{id!=\"/\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (pod,interface) / max (increase (container_network_receive_packets_total{id!=\"/\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (pod,interface)",
     "legendFormat": "{{pod}}/{{interface}}(Error-Input)"
    },
    {
     "expr": "max (increase (container_network_transmit_errors_total{id!=\"/\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (pod,interface) / max (increase (container_network_receive_packets_total{id!=\"/\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (pod,interface)",
     "legendFormat": "{{pod}}/{{interface}}(Error-Output)"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "description": "容器 CPU 使用量相对于限制值的百分比。 ",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(irate(container_cpu_usage_seconds_total{pod=~\"$pod\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\"}[1m])) by (container,namespace,pod) / max(container_spec_cpu_quota{pod=~\"$pod\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\"}/100000) by (container,namespace,pod) or on() vector(0)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "CPU Usage By Cores",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(irate(container_cpu_usage_seconds_total{pod=~\"$pod\",container!=\"\",container!=\"POD\",namespace=~\"$namespace\"}[1m])) by (pod,container,namespace)or on() vector(0)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "CPU Load(10s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(container_cpu_load_average_10s{namespace=~\"${namespace}\", pod=~\"${pod}\", container!=\"\", container!=\"POD\"} / 1000)by(pod,container)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "CPU Throttled Percent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max (rate (container_cpu_cfs_throttled_seconds_total{image!=\"\", container!=\"\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (container,pod) / max (rate (container_cpu_cfs_periods_total{image!=\"\", container!=\"\", namespace=~\"$namespace\", pod=~\"$pod\"}[1m])) by (container,pod) or on() vector(0)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Network Bandwidth Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "max (rate (container_network_receive_bytes_total{image!=\"\",namespace=~\"$namespace\", pod_name=~\"$pod\"}[1m])) by(pod)",
     "legendFormat": "{{pod}}-Input"
    },
    {
     "expr": "-max (rate (container_network_transmit_bytes_total{image!=\"\",namespace=~\"$namespace\", pod_name=~\"$pod\"}[1m]))by(pod)",
     "legendFormat": "{{pod}}-Output"
    }
   ]
  },
  {
   "title": "Network Socket",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(container_sockets{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\"}) by (container,pod)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "File System",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "max (rate(container_fs_reads_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\"}[1m]))by (container,pod)",
     "legendFormat": "{{pod}}/{{container}}(Read)"
    },
    {
     "expr": "max (rate(container_fs_writes_bytes_total{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\"}[1m])) by (container,pod)",
     "legendFormat": "{{pod}}/{{container}}(Write)"
    }
   ]
  },
  {
   "title": "Process Number",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(container_processes{namespace=~\"$namespace\", pod=~\"$pod\", container!=\"\"}) by (container,pod)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  }
 ]
}