{
 "title": "有状态应用监控",
 "description": "Kubernetes StatefulSet Overview",
 "tags": [
  "kubernetes",
  "statefulset"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_statefulset_created, namespace)"
    }
   },
   {
    "name": "name",
    "label": "StatefulSet",
    "query": {
     "query": "label_values(kube_statefulset_created{namespace=\"$namespace\"}, statefulset)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Namespace",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_namespace_labels{namespace=\"$namespace\"})by(namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Age",
   "type": "stat",
   "description": "Time since StatefulSet created.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(kube_statefulset_created{namespace=\"$namespace\",statefulset=\"$name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Generation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_statefulset_metadata_generation{namespace=\"$namespace\", statefulset=\"$name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{namespace=\"$namespace\",statefulset=\"$name\"}/kube_statefulset_replicas{namespace=\"$namespace\",statefulset=\"$name\"}",
     "legendFormat": "$name"
    }
   ]
  },
  {
   "title": "Replicas(Pods)",
   "type": "stat",
   "description": "Number of desired replicas.",
   "gridPos": { "h": 4, "w": 7, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_statefulset_replicas{statefulset=\"$name\",namespace=\"$namespace\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "max(kube_statefulset_status_replicas_ready{statefulset=\"$name\",namespace=\"$namespace\"})",
     "legendFormat": "Ready"
    },
    {
     "expr": "max(kube_statefulset_status_replicas_ready{statefulset=\"$name\",namespace=\"$namespace\"}) / max(kube_statefulset_replicas{statefulset=\"$name\",namespace=\"$namespace\"})",
     "legendFormat": "Percent"
    }
   ]
  },
  {
   "title": "Replica Trend",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(kube_statefulset_replicas{statefulset=\"$name\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "Desired"
    },
    {
     "expr": "max(kube_statefulset_status_replicas{statefulset=\"$name\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "Current"
    },
    {
     "expr": "min(kube_statefulset_status_replicas_ready{statefulset=\"$name\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "Ready"
    },
    {
     "expr": "min(kube_statefulset_status_replicas_available{statefulset=\"$name\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "Available"
    },
    {
     "expr": "min(kube_statefulset_status_replicas_updated{statefulset=\"$name\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "Updated"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "table",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",created_by_name=\"$name\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\"} * (kube_pod_status_phase{namespace=\"$namespace\"} > 0)) by (uid, phase)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_status_ready{namespace=\"$namespace\"} * (kube_pod_status_ready{namespace=\"$namespace\"} > 0)) by (uid, condition)",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - max(kube_pod_created{namespace=\"$namespace\"}) by (uid)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(max(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}) by (uid, container)) by (uid)"
    }
   ]
  },
  {
   "title": "Focus Error Events",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceil(sum(increase(eventer_events_error_total{namespace='$namespace', kind=\"Statefulset\", name=\"$name\"}[1h])) by (kind, name, reason)) > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(label_replace(group by (target_kind, target_name)(kube_resource_relationship{namespace=\"$namespace\", kind=\"StatefulSet\", name=\"$name\"}>0), \"name\", \"$1\", \"target_name\", \"(.*)\"), \"kind\", \"$1\", \"target_kind\", \"(.*)\") * on(name, kind)  group_right() ceil(sum(increase(eventer_events_error_total{namespace='$namespace'}[1h])) by (kind, name, reason)) > 0"
    }
   ]
  },
  {
   "title": "MetaInfo",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "fields": [
      { "jsonPath": "$.metadata.labels", "language": "jsonata", "name": "Labels" },
      { "jsonPath": "$.metadata.annotations", "language": "jsonata", "name": "Annotations" },
      { "jsonPath": "$.spec.serviceName", "language": "jsonata", "name": "ServiceName" }
     ],
     "method": "GET",
     "resource": { "gvk": "apps/v1__statefulsets", "name": "$name", "namespace": "$namespace" },
     "urlPath": "/apis/apps/v1/namespaces/$namespace/statefulsets/$name"
    }
   ]
  },
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "group by (service) (label_replace(group by (name) (label_replace(group by(target_name) (kube_resource_relationship{namespace=\"$namespace\", kind=\"StatefulSet\", name=\"$name\", target_kind=\"Pod\"}>0), \"name\", \"$1\", \"target_name\", \"(.*)\") * on(target_name) group_right() kube_resource_relationship{kind=\"Endpoints\", target_kind=\"Pod\"}>0), \"service\", \"$1\", \"name\", \"(.*)\")) * on(service) group_right() group by (cluster_ip, uid, service) (kube_service_info{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PersistentVolumeClaim",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "group by (persistentvolumeclaim, storageclass, node, volumename) (group by (persistentvolumeclaim) (label_replace(group by (target_name) (kube_resource_relationship{namespace=\"$namespace\", kind=\"StatefulSet\", name=\"$name\", target_kind=\"PersistentVolumeClaim\"}>0), \"persistentvolumeclaim\", \"$1\", \"target_name\", \"(.*)\")) * on (persistentvolumeclaim) group_right() kube_persistentvolumeclaim_info{namespace=\"$namespace\"}) * on (persistentvolumeclaim) group_left() kube_persistentvolumeclaim_status_phase{phase=\"Bound\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() sum(container_spec_memory_limit_bytes{namespace=\"$namespace\",container!=\"\"}) by (pod))",
     "legendFormat": "Total"
    },
    {
     "expr": "max(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() sum(container_spec_memory_limit_bytes{namespace=\"$namespace\",container!=\"\"}) by (pod))",
     "legendFormat": "Single Pod"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "展示该工作负载的每个 Pod 内存使用量。",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max by(container, pod, image) (container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\", container!=\"POD\"}))by (container, pod, image)",
     "legendFormat": "Usage: {{pod}}/{{container}}  Image: {{image}}"
    },
    {
     "expr": "max(avg(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max by(container, pod, image) (kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"}))by (container, pod))by(container)",
     "legendFormat": "Request: {{container}}"
    },
    {
     "expr": "max(avg(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max by(container, pod) (kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\"}))by (container, pod))by(container)",
     "legendFormat": "Limit: {{container}}"
    }
   ]
  },
  {
   "title": "Memory Request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "Total"
    },
    {
     "expr": "max(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() sum(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "Single Pod"
    }
   ]
  },
  {
   "title": "CPU Limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "Total"
    },
    {
     "expr": "max(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "Single Pod"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "展示该工作负载每个 Pod 的 CPU 使用量。",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"\",container!=\"POD\"}[5m])) by (pod, container,image)",
     "legendFormat": "{{pod}}/{{container}} Image:{{image}}"
    },
    {
     "expr": "group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\"}) by (pod, container,image)",
     "legendFormat": "Limit: {{container}}"
    },
    {
     "expr": "group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\"}) by (pod, container,image)",
     "legendFormat": "Request: {{container}}"
    }
   ]
  },
  {
   "title": "CPU Request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "Total"
    },
    {
     "expr": "max(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() sum(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\"}) by (pod))",
     "legendFormat": "Single Pod"
    }
   ]
  },
  {
   "title": "CPU User Time(%)",
   "type": "timeseries",
   "description": "用户级 CPU 使用率相对于整体 CPU 使用量的比例。",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() (max(rate(container_cpu_user_seconds_total{namespace=\"$namespace\",container!=\"\"}[5m])) by (pod, container,image) / max(rate(container_cpu_user_seconds_total{namespace=\"$namespace\",container!=\"\"}[5m])+rate(container_cpu_system_seconds_total{namespace=\"$namespace\",container!=\"\"}[5m])) by (pod,container,image))) by (pod,container,image)",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Sockets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() sum(container_sockets{namespace=\"$namespace\",container!=\"\"}) by (pod))"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "stat",
   "description": "The number of network errors including receiving and transmitting.",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() (sum(container_network_receive_errors_total{namespace=\"$namespace\"}) by (pod) + sum(container_network_transmit_errors_total{namespace=\"$namespace\"}) by (pod)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max(rate(container_network_receive_bytes_total{namespace=\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}-In"
    },
    {
     "expr": "-sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max(rate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}-Out"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max(rate(container_fs_reads_bytes_total{namespace=\"$namespace\", container!=\"POD\", container!=\"\"}[5m])) by (pod,container)",
     "legendFormat": "{{pod}}/{{container}}(Read)"
    },
    {
     "expr": "group(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() max(rate(container_fs_writes_bytes_total{namespace=\"$namespace\", container!=\"POD\", container!=\"\"}[5m])) by (pod,container)",
     "legendFormat": "{{pod}}/{{container}}(Write)"
    }
   ]
  },
  {
   "title": "Network In",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\"}[5m])) by (pod))"
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum(kube_pod_info{namespace=\"$namespace\",created_by_kind=\"StatefulSet\",pod_ip!=\"\", created_by_name=\"$name\"}) by (pod)\n* on(pod) group_right() sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[5m])) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}