kind: pipeline
name: build-rainbond-allinone

platform:
  os: linux
  arch: arm64

trigger:
  event:
    include:
    - custom

node:
  city: sydney


steps:
- name: clone rainbond-ui-cloud
  image: alpine/git
  environment:
    BRANCH:
      from_secret: branch
    VERSION:
      from_secret: version
    GITLAB_USER:
      from_secret: gitlab_user
    GITLAB_PASS:
      from_secret: gitlab_pass
    OPERATOR_BRANCH:
      from_secret: operator_branch
  commands:
  - git clone -b $BRANCH --depth=1 https://$GITLAB_USER:$GITLAB_PASS@git.goodrain.com/goodrain/rainbond-ui-cloud.git
  - git clone -b $BRANCH --depth=1 https://$GITLAB_USER:$GITLAB_PASS@git.goodrain.com/goodrain/rainbond-console-cloud.git
  - git clone -b $OPERATOR_BRANCH --depth=1 https://ghproxy.com/https://github.com/goodrain/rainbond-operator.git

- name: build rainbond-ui-cloud dist
  image: node:14
  environment:
    ALLINONE: true
  commands:
  - cd rainbond-ui-cloud
  - yarn config set registry https://registry.npm.taobao.org
  - yarn install
  - yarn run build

- name: build rainbond-ui-cloud
  image: rainbond/docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run
  environment:
    VERSION:
      from_secret: version
    IMAGE_NAMESPACE:
      from_secret: image_namespace
    IMAGE_DOMAIN:
      from_secret: image_namespace
  commands:
  - sleep 10 # give docker enough time to start
  - cd rainbond-ui-cloud
  - docker build -t $IMAGE_NAMESPACE/rainbond-ui:$VERSION .

- name: build rainbond-operator
  image: rainbond/docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run
  environment:
    VERSION:
      from_secret: version
    DOMESTIC_DOCKER_USERNAME:
      from_secret: domestic_docker_username
    DOMESTIC_DOCKER_PASSWORD:
      from_secret: domestic_docker_password
  commands:
  - sleep 10 # give docker enough time to start
  - cd rainbond-operator
  - docker build --build-arg ARCH=arm64 -t registry.cn-hangzhou.aliyuncs.com/goodrain/rainbond-operator:$VERSION .
  - docker login registry.cn-hangzhou.aliyuncs.com -u "$DOMESTIC_DOCKER_USERNAME" -p $DOMESTIC_DOCKER_PASSWORD
  - docker push registry.cn-hangzhou.aliyuncs.com/goodrain/rainbond-operator:$VERSION

- name: build rainbond-console
  image: rainbond/docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run
  environment:
    TRAVIS_PULL_REQUEST:
      from_secret: false
    VERSION:
      from_secret: version
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
    ADAPTOR_VERSION:
      from_secret: adaptor_version
    GITLAB_USER:
      from_secret: gitlab_user
    GITLAB_PASS:
      from_secret: gitlab_pass
    IMAGE_DOMAIN:
      from_secret: image_domain
    IMAGE_NAMESPACE:
      from_secret: image_namespace
    GOOS: linux
  commands:
  - rm -rf rainbond-ui
  - cd rainbond-console-cloud
  - BUILD_ARCH=arm64 ./release.sh allinone_arm
  when:
    event:
      include:
      - custom

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}

---

kind: pipeline
name: build-rainbond-region

platform:
  os: linux
  arch: arm64

trigger:
  event:
    include:
    - custom

node:
  city: sydney

steps:
- name: clone rainbond
  image: alpine/git
  environment:
    VERSION:
      from_secret: version
    GITLAB_USER:
      from_secret: gitlab_user
    GITLAB_PASS:
      from_secret: gitlab_pass
  commands:
  - git clone -b $VERSION --depth=1 https://$GITLAB_USER:$GITLAB_PASS@git.goodrain.com/goodrain/rainbond.git

- name: build rainbond
  image: rainbond/docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run
  environment:
    VERSION:
      from_secret: version
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
    IMAGE_DOMAIN:
      from_secret: image_domain
    DOCKER_NAMESPACE:
      from_secret: image_namespace
    GOOS: linux
    GOARCH: arm64
  commands:
  - sleep 10 # give docker enough time to start
  - cd rainbond
  - BUILD_GOARCH=arm64 BUILD_BASE_IMAGE_VERSION=3.7 ./release.sh all push
  when:
    event:
      include:
      - custom


services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}

depends_on:
- build-rainbond-allinone

---

kind: pipeline
name: build-rainbond-package

platform:
  os: linux
  arch: arm64

trigger:
  event:
    include:
    - custom

node:
  city: sydney

steps:    
- name: build rainbond package
  image: rainbond/docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run
  environment:
    RBD_VER:
      from_secret: version
    IMAGE_DOMAIN:
      from_secret: image_domain
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
    GOOS: linux
    GOARCH: arm64
  commands:
  - docker login image.goodrain.com -u "$DOCKER_USERNAME" -p $DOCKER_PASSWORD
  - sleep 10 # give docker enough time to start
  - chmod +x enterprise_offline_package.sh
  - ./enterprise_offline_package.sh
  when:
    event:
      include:
      - custom

- name: push rainbond package
  image: rainbond/docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run
  environment:
    AKI:
      from_secret: aki
    AKS:
      from_secret: aks
    GOOS: linux
    GOARCH: arm64
  commands:
  - sleep 10 # give docker enough time to start
  - wget https://gosspublic.alicdn.com/ossutil/1.7.11/ossutilarm64 && chmod +x ossutilarm64
  - ./ossutilarm64 config -e oss-cn-shanghai.aliyuncs.com -i $AKI -k $AKS
  - ./ossutilarm64 cp -rf rainbond-offline-*.tgz oss://rainbond-pkg/offline/5.3-enterprise/
  when:
    event:
      include:
      - custom

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}

depends_on:
- build-rainbond-allinone
- build-rainbond-region
