{
 "title": "集群监控概览",
 "tags": [
  "kubernetes",
  "overview"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Node Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_node_info)" }
   ]
  },
  {
   "title": "Pod Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_pod_info)" }
   ]
  },
  {
   "title": "Node Request Memory Average Percent",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(kube_pod_container_resource_requests{resource=\"memory\"})by (node)/sum(kube_node_status_capacity{resource=\"memory\"})by(node))"
    }
   ]
  },
  {
   "title": "Node Request CPU Average Percent",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(kube_pod_container_resource_requests{resource=\"cpu\"})by (node)/sum(kube_node_status_capacity{resource=\"cpu\"})by(node))"
    }
   ]
  },
  {
   "title": "API Server Success Request Percent",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(apiserver_request_total{code=~\"20.*\",verb=~\"GET|LIST\"}[5m]))/sum(irate(apiserver_request_total{verb=~\"GET|LIST\"}[5m]))",
     "legendFormat": "APIServer"
    }
   ]
  },
  {
   "title": "Namespace Overview",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "count(kube_pod_info{}) by (namespace)"
    },
    {
     "expr": "count(kube_service_info{}) by(namespace)"
    },
    {
     "expr": "count(kube_pod_container_info{}) by(namespace)"
    },
    {
     "expr": "count(kube_configmap_info{}) by(namespace)",
     "legendFormat": "configmap"
    },
    {
     "expr": "count(kube_secret_info{}) by(namespace)",
     "legendFormat": "secret"
    },
    {
     "expr": "count(kube_deployment_created{}) by (namespace)"
    },
    {
     "expr": "count(kube_statefulset_created{}) by (namespace)"
    },
    {
     "expr": "count(kube_job_created{}) by (namespace)"
    },
    {
     "expr": "count(kube_cronjob_created{}) by (namespace)"
    },
    {
     "expr": "count(kube_pod_status_ready{condition=\"false\"}==1) by(namespace) - (count(kube_pod_status_phase{phase=\"Succeeded\"}==1) by(namespace) or vector(0)) or count(kube_pod_status_ready{condition=\"false\"}==1) by(namespace)"
    },
    {
     "expr": "count(kube_deployment_status_replicas_ready{}<kube_deployment_spec_replicas{}) by (namespace)"
    },
    {
     "expr": "count(kube_statefulset_status_replicas_ready{}<kube_statefulset_replicas{}) by (namespace)"
    },
    {
     "expr": "count(kube_daemonset_status_number_unavailable{}>0)by(namespace)"
    },
    {
     "expr": "count(kube_job_status_failed{} == 1) by (namespace)"
    },
    {
     "expr": "count(kube_daemonset_created{}) by (namespace)"
    },
    {
     "expr": "count(kube_persistentvolumeclaim_info{}) by (namespace)"
    }
   ]
  },
  {
   "title": "Node Memory Usage (Top 10)",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(label_replace(topk(10, 1-(node_memory_MemAvailable_bytes{} / node_memory_MemTotal_bytes{})), \"node_ip\", \"$1\", \"instance\", \"(.*):(.*)\"))by(node_ip)",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "Node CPU Usage (Top 10)",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, sum(label_replace(1 - sum(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) by (instance) / sum(rate(node_cpu_seconds_total[1m])) by (instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(host_ip))",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "Node Disk Usage (Top 10)",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, sum(label_replace(1-node_filesystem_free_bytes{mountpoint=\"/\"}/node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"},\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(host_ip))",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "Node Network In (Top 10)",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(10, sum(label_replace(max(irate(node_network_receive_bytes_total{}[1m])) by (instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(host_ip))",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "Node Network Out (Top 10)",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(10, sum(label_replace(max(irate(node_network_transmit_bytes_total{}[1m])) by (instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(host_ip))",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "Node Sockets Count(Top 10)",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(10, sum(label_replace(max(node_sockstat_TCP_alloc) by (instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(host_ip))",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage(Top10)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, sum (container_memory_working_set_bytes{container !=\"\",container!=\"POD\"}) by (container))",
     "legendFormat": "WorkingSet：[Container]:{{ container }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage/Limit(Top10)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, avg(container_memory_working_set_bytes{container!=\"\"}/(container_spec_memory_limit_bytes!=0)) by (container, pod, namespace))",
     "legendFormat": "WorkingSet：[Container]:{{ container }}"
    }
   ]
  },
  {
   "title": "Container CPU Usage(Top10)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(container_cpu_usage_seconds_total{container !=\"\",container!=\"POD\"}[2m])) by (container))",
     "legendFormat": "Usage [Container]:{{ container}}"
    }
   ]
  },
  {
   "title": "Container Network",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "topk(10, sum(irate(container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\"}[2m])) by (pod))",
     "legendFormat": "Receive: [Pod]:{{pod}}"
    },
    {
     "expr": "-topk(10, sum(irate(container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\"}[2m])) by (pod))",
     "legendFormat": "Transmit: [Pod]:{{pod}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage/Limit (Top 10)",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, avg(container_memory_working_set_bytes{container!=\"\"}/(container_spec_memory_limit_bytes!=0)) by (container, pod, namespace))",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "Container CPU Usage (Top 10)",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, sum(irate(container_cpu_usage_seconds_total{container!=\"\",container!=\"POD\"}[1m])) by (container,pod,namespace)or on() vector(0))",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "Container Socket Count(Top 10)",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, sum(container_sockets{container!=\"\"}) by (container,pod,namespace)or on() vector(0))",
     "legendFormat": "{{node_ip}}"
    }
   ]
  }
 ]
}