{
 "title": "集群节点监控详情",
 "tags": [
  "kubernetes",
  "node"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_node_info{system_uuid!=\"\"}, internal_ip)"
    }
   },
   { "name": "clusterUid", "query": "8749" }
  ]
 },
 "panels": [
  {
   "title": "System Run Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{instance=~\".*$node.*\"})"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_memory_MemTotal_bytes{instance=~\".*$node.*\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pod List",
   "type": "table",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "group (kube_pod_info{host_ip=~\"$node\"})by(created_by_kind, created_by_name,host_network,pod_ip,pod,priority_class,namespace)",
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    },
    {
     "expr": " min(kube_pod_info{host_ip=~\"$node\"})by(pod) * on(pod) group_right() max(kube_pod_status_phase{}==1) by (pod, phase) "
    },
    {
     "expr": " min(kube_pod_info{host_ip=~\"$node\"})by(pod) * on(pod) group_right() sum(container_memory_working_set_bytes) by (pod) "
    },
    {
     "expr": " min(kube_pod_info{host_ip=~\"$node\"})by(pod) * on(pod) group_right() sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[5m])) by (pod)"
    },
    {
     "expr": "min(kube_pod_info{host_ip=~\"$node\"})by(pod) * on(pod) group_right() max(time()-kube_pod_start_time) by (pod) "
    },
    {
     "expr": "min(kube_pod_info{host_ip=~\"$node\"})by(pod) * on(pod) max(kube_pod_status_ready{condition=\"true\"}) by (pod) or on() vector(0)"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\".*$node.*\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "Node Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "expr": "group(kube_node_info{node=~\".*.$node\"})by(node, pod_cidr, kubelet_version,kernel_version,container_runtime_version)",
     "fields": [
      { "jsonPath": "" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{node=~\".*.$node\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "kube_node_status_capacity_pods{node=~\".*.$node\"}",
     "legendFormat": "Capacity"
    }
   ]
  },
  {
   "title": "Node Resource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Boot Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "time()-node_boot_time_seconds" }
   ]
  },
  {
   "title": "CPU Usage Percent (5m)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\".*$node.*\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU IOwait（5m）",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\".*$node.*\",mode=\"iowait\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((1 - (node_memory_MemAvailable_bytes{instance=~\".*$node.*\"} / (node_memory_MemTotal_bytes{instance=~\".*$node.*\"})))* 100)"
    }
   ]
  },
  {
   "title": "File Descriptor Usage Percent",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node_filefd_allocated{instance=~\".*$node.*\"})/max(node_filefd_maximum{instance=~\".*$node.*\"})"
    }
   ]
  },
  {
   "title": "Root Partition Usage Percent",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100 - ((node_filesystem_free_bytes{instance=~\".*$node.*\",mountpoint=\"/\"} * 100) / node_filesystem_size_bytes {instance=~\".*$node.*\",mountpoint=\"/\"}))"
    }
   ]
  },
  {
   "title": "Network Socket Alloc",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node_sockstat_TCP_alloc{instance=~\".*$node.*\"})"
    }
   ]
  },
  {
   "title": "Average System Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\".*$node.*\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=~\".*$node.*\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=~\".*$node.*\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Disk File System",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(node_filesystem_size_bytes{instance=~'.*$node.*',fstype=~\"ext4|xfs\"}) by (device, fstype, mountpoint)"
    },
    {
     "expr": "(max(node_filesystem_size_bytes{instance=~'.*$node.*',fstype=~\"ext4|xfs\"}) by (device, fstype, mountpoint) - max(node_filesystem_free_bytes{instance=~'.*$node.*',fstype=~\"ext4|xfs\"}) by (device, fstype, mountpoint))/max(node_filesystem_size_bytes{instance=~'.*$node.*',fstype=~\"ext4|xfs\"}) by (device, fstype, mountpoint)"
    },
    {
     "expr": "max(node_filesystem_size_bytes{instance=~'.*$node.*',fstype=~\"ext4|xfs\"}) by (device, fstype, mountpoint)-max(node_filesystem_free_bytes{instance=~'.*$node.*',fstype=~\"ext4|xfs\"}) by (device, fstype, mountpoint)"
    },
    {
     "expr": "max(node_filesystem_avail_bytes{instance=~'.*$node.*',fstype=~\"ext4|xfs\"}) by (device, fstype, mountpoint)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "这里CPU使用率、磁盘每秒IO操作耗时使用率 % 此图每根线的含义：\n\nSystem，是CPU系统部分CPU时间片占总CPU时间片的百分比，也就是CPU系统部分的CPU使用率%\nUser，是CPU User部分CPU时间片占总CPU时间片的百分比，也就是CPU User部分的CPU使用率%\nIowait，是CPU Iowait部分CPU时间片占总CPU时间片的百分比，也就是CPU Iowait部分的CPU使用率%\n\n{{device}}_每秒I/O操作% 这根线是每个设备（如vda），IO操作的时间占总IO时间的占比，也就是此设备的IO使用率 %\nnode_disk_io_time_seconds_total：\n磁盘花费在输入/输出操作上的毫秒数。该值为累加值。（Milliseconds Spent Doing I/Os）\n\nirate(node_disk_io_time_seconds_total[1m])：\n计算每秒的速率：(last值-last前一个值)/时间戳差值，即：1秒钟内磁盘花费在I/O操作的时间占比。",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\".*$node.*\",mode=\"system\"}[1m]))",
     "legendFormat": "System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\".*$node.*\",mode=\"user\"}[1m]))",
     "legendFormat": "User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\".*$node.*\",mode=\"iowait\"}[1m]))",
     "legendFormat": "Iowait"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\".*$node.*\"}[1m])",
     "legendFormat": "{{device}}_I/O operations per second%"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\".*$node.*\"}",
     "legendFormat": "Total memory"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\".*$node.*\"} - node_memory_MemAvailable_bytes{instance=~\".*$node.*\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\".*$node.*\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Disk Read / Write Rate (IOPs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\".*$node.*\"}[1m])",
     "legendFormat": "{{device}}_Read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\".*$node.*\"}[1m])",
     "legendFormat": "{{device}}_Write"
    }
   ]
  },
  {
   "title": "Disk Read / Write ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\".*$node.*\"}[1m])",
     "legendFormat": "{{device}}_Read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\".*$node.*\"}[1m])",
     "legendFormat": "{{device}}_Write"
    }
   ]
  },
  {
   "title": "Disk IO Read / Write Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{instance=~\".*$node.*\"}[1m])",
     "legendFormat": "{{device}}_Read"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{instance=~\".*$node.*\"}[1m])",
     "legendFormat": "{{device}}_Write"
    }
   ]
  },
  {
   "title": "Disk File System Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(max(node_filesystem_size_bytes{instance=~'.*$node.*',fstype=~\"ext4|xfs\"}) by (device, fstype, mountpoint) - max(node_filesystem_free_bytes{instance=~'.*$node.*',fstype=~\"ext4|xfs\"}) by (device, fstype, mountpoint))/max(node_filesystem_size_bytes{instance=~'.*$node.*',fstype=~\"ext4|xfs\"}) by (device, fstype, mountpoint)"
    }
   ]
  },
  {
   "title": "Disk File System Usage (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(node_filesystem_size_bytes{instance=~'.*$node.*',fstype=~\"ext4|xfs\"}) by (device, fstype, mountpoint) - max(node_filesystem_free_bytes{instance=~'.*$node.*',fstype=~\"ext4|xfs\"}) by (device, fstype, mountpoint)"
    }
   ]
  },
  {
   "title": "Disk File System Available (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(node_filesystem_avail_bytes{instance=~'.*$node.*',fstype=~\"ext4|xfs\"}) by (device, fstype, mountpoint)"
    }
   ]
  },
  {
   "title": "Network Traffic Receive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'.*$node.*',device!~'tap.*'}[5m])",
     "legendFormat": "{{device}}_in"
    }
   ]
  },
  {
   "title": "Network Traffic Transmit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'.*$node.*',device!~'tap.*'}[5m])",
     "legendFormat": "{{device}}_out"
    }
   ]
  },
  {
   "title": "TCP Connection",
   "type": "graph",
   "description": "CurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n\nActiveOpens - 已从 CLOSED 状态直接转换到 SYN-SENT 状态的 TCP 平均连接数(1分钟内)\n\nPassiveOpens - 已从 LISTEN 状态直接转换到 SYN-RCVD 状态的 TCP 平均连接数(1分钟内)\n\nTCP_alloc - 已分配（已建立、已申请到sk_buff）的TCP套接字数量\n\nTCP_inuse - 正在使用（正在侦听）的TCP套接字数量\n\nTCP_tw - 等待关闭的TCP连接数",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'.*$node.*'}",
     "legendFormat": "ESTABLISHED"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~'.*$node.*'}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=~'.*$node.*'}[1m])",
     "legendFormat": "ActiveOpens"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=~'.*$node.*'}[1m])",
     "legendFormat": "PassiveOpens"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~'.*$node.*'}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=~'.*$node.*'}",
     "legendFormat": "TCP_inuse"
    }
   ]
  }
 ]
}