{
 "title": "组件监控",
 "description": "组件监控可视化",
 "tags": [
  "other",
  "other",
  "other",
  "other"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datacenter", "label": "集群", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Rainbond组件状态",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "组件状态",
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{namespace =\"rbd-system\"} - 0"
    },
    {
     "expr": "kube_pod_container_status_restarts_total{namespace =\"rbd-system\"} - 0"
    }
   ]
  },
  {
   "title": "DB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "状态",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_up{namespace=\"rbd-system\"} - 0",
     "legendFormat": "status"
    }
   ]
  },
  {
   "title": "MySQL 正常运行时间",
   "type": "gauge",
   "description": "mysqld 服务器进程最后一次重启的时间。",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_uptime{namespace=\"rbd-system\"}"
    }
   ]
  },
  {
   "title": "当前的 QPS",
   "type": "stat",
   "description": "**Current QPS**\n\n根据 MySQL 的 ``SHOW STATUS`` 命令所返回的查询结果计算，它是服务器在最后一秒内执行的查询语句数。\n\n这个值包括存储过程当中所执行的 SQL 语句数量，与 ``Questions`` 所统计的结果不同，他不包含 ``COM_PING `` 与 ``COM_STATISTICS `` 命令返回的结果。",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "irate(mysql_global_status_queries{namespace=\"rbd-system\"}[5m])"
    }
   ]
  },
  {
   "title": "InnoDB 缓冲池大小",
   "type": "graph",
   "description": "InnoDB 维护了一个缓冲池，用于在内存当中进行数据缓存与索引。\n\n了解 InnoDB 缓冲池是如何工作地，就可以利用它将频繁访问的数据存储在内存当中。这也是 MySQL 性能调优的重要一个技巧。\n\n最终的目的就是缓存结果，在大多数情况下，他的值应该是主机内存的 60% ~ 90% 之间。",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_variables_innodb_buffer_pool_size{namespace=\"rbd-system\"}"
    }
   ]
  },
  {
   "title": "MySQL 网络流量",
   "type": "graph",
   "description": "在这个统计图内部我们可以看到 MySQL 产生了多少网络流量。\n\n* 出站流量是 MySQL 发送的网络流量。\n* 入站流量是 MySQL 接收的网络流量。",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "irate(mysql_global_status_bytes_received{namespace=\"rbd-system\"}[5m])",
     "legendFormat": "入站流量"
    },
    {
     "calculatedInterval": "2m",
     "expr": "irate(mysql_global_status_bytes_sent{namespace=\"rbd-system\"}[5m])",
     "legendFormat": "出站流量"
    }
   ]
  },
  {
   "title": "MySQL 异常中断的连接",
   "type": "graph",
   "description": "当某个客户端连接到 MySQL 时，连接异常中断，而 MySQL 会将该信息保存在异常表当中。\n\n如果没有连接异常的数量到达 ``max_connect_errors`` 的值，mysqld 将会假定有错误并且进一步阻止客户的进一步连接。如果要允许该客户端再次连接，需要执行 ``FLUSH HOSTS`` 命令。",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "irate(mysql_global_status_aborted_connects{namespace=\"rbd-system\"}[5m])",
     "legendFormat": "异常中断的客户端 (尝试连接)"
    },
    {
     "calculatedInterval": "2m",
     "expr": "irate(mysql_global_status_aborted_clients{namespace=\"rbd-system\"}[5m])",
     "legendFormat": "异常中断的客户端 (超时)"
    }
   ]
  },
  {
   "title": "MySQL 慢查询",
   "type": "graph",
   "description": "慢查询的定义是比 ``long_query_time`` 所设置的值还要慢的查询，例如你把 ``long_query_time`` 的值设置为 3 ，那么需要超过 3 秒之后才能够完成的查询就是慢查询，这些查询会被统计到本图当中。",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "irate(mysql_global_status_slow_queries{namespace=\"rbd-system\"}[5m])",
     "legendFormat": "慢查询语句"
    }
   ]
  },
  {
   "title": "ETCD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ETCD leader状态",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(etcd_server_has_leader) - 0",
     "legendFormat": "status"
    }
   ]
  },
  {
   "title": "leader变更次数",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_server_leader_changes_seen_total",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "进程常驻内存",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 14, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{}) by (instance)",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "提交失败数量/7d",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_server_proposals_failed_total{component=\"etcd\",job=\"etcd\"}[7d])"
    }
   ]
  },
  {
   "title": "后端调用提交的延迟分布",
   "type": "graph",
   "description": "99%请求的时延",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,rate(etcd_disk_backend_commit_duration_seconds_bucket{job=~\"etcd\"}[30m]))"
    }
   ]
  },
  {
   "title": "Chaos",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {}
   ]
  },
  {
   "title": "状态",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "builder_exporter_health_status - 0",
     "legendFormat": "status"
    }
   ]
  },
  {
   "title": "构建任务",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "builder_exporter_builder_task_number",
     "legendFormat": "构建任务总数"
    },
    {
     "expr": "builder_exporter_builder_max_concurrent_task",
     "legendFormat": "构建任务数上限"
    },
    {
     "expr": "builder_exporter_builder_task_error",
     "legendFormat": "构建任务失败数量"
    }
   ]
  },
  {
   "title": "Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "repeat": "datacenter",
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "状态",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "builder_exporter_health_status - 0",
     "legendFormat": "status"
    }
   ]
  },
  {
   "title": "延迟统计",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(gateway_upstream_latency_seconds_count[1m]))",
     "legendFormat": "延迟总次数(1m)"
    },
    {
     "expr": "sum(gateway_upstream_latency_seconds_sum)",
     "legendFormat": "延迟总时间"
    }
   ]
  },
  {
   "title": "客户端请求与响应的总数",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gateway_request_duration_seconds_count)",
     "legendFormat": "客户端请求总次数"
    },
    {
     "expr": "sum(gateway_response_duration_seconds_count)",
     "legendFormat": "响应总次数"
    },
    {
     "expr": "sum(gateway_request_duration_seconds_sum)",
     "legendFormat": "客户端请求总时间"
    },
    {
     "expr": "sum(gateway_response_duration_seconds_sum)",
     "legendFormat": "响应总时间"
    }
   ]
  },
  {
   "title": "网关策略数量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_active_server{type=\"http\"}",
     "legendFormat": "网关Server数量(http)"
    },
    {
     "expr": "nginx_active_server{type=\"tcp\"}",
     "legendFormat": "网关Server数量(tcp)"
    }
   ]
  },
  {
   "title": "在规定请求时间(bucket)内, 客户端请求与响应的情况",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gateway_request_duration_seconds_bucket[1m]))",
     "legendFormat": "request: total"
    },
    {
     "expr": "sum(rate(gateway_request_duration_seconds_bucket{status=~\"^2.*\"}[1m]))",
     "legendFormat": "request: status: 20*"
    },
    {
     "expr": "sum(rate(gateway_request_duration_seconds_bucket{status=~\"^3.*\"}[1m]))",
     "legendFormat": "request: status: 30*"
    },
    {
     "expr": "sum(rate(gateway_request_duration_seconds_bucket{status=~\"^4.*\"}[1m]))",
     "legendFormat": "request: status: 40*"
    },
    {
     "expr": "sum(rate(gateway_request_duration_seconds_bucket{status=~\"^5.*\"}[1m]))",
     "legendFormat": "request: status: 50*"
    },
    {
     "expr": "-sum(rate(gateway_response_duration_seconds_bucket[1m]))",
     "legendFormat": "response: total"
    },
    {
     "expr": "-sum(rate(gateway_response_duration_seconds_bucket{status=~\"^2.*\"}[1m]))",
     "legendFormat": "response: status: 20*"
    },
    {
     "expr": "-sum(rate(gateway_response_duration_seconds_bucket{status=~\"^3.*\"}[1m]))",
     "legendFormat": "response: status: 30*"
    },
    {
     "expr": "-sum(rate(gateway_response_duration_seconds_bucket{status=~\"^4.*\"}[1m]))",
     "legendFormat": "response: status: 40*"
    },
    {
     "expr": "-sum(rate(gateway_response_duration_seconds_bucket{status=~\"^5.*\"}[1m]))",
     "legendFormat": "response: status: 50*"
    }
   ]
  },
  {
   "title": "MQ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {}
   ]
  },
  {
   "title": "状态",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "acp_mq_exporter_health_status - 0",
     "legendFormat": "status"
    }
   ]
  },
  {
   "title": "scrapes total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "acp_mq_exporter_scrapes_total" }
   ]
  },
  {
   "title": "Worker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "repeat": "datacenter",
   "targets": [
    {}
   ]
  },
  {
   "title": "状态",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "worker_exporter_health_status - 0",
     "legendFormat": "status"
    }
   ]
  },
  {
   "title": "worker 失败率",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(worker_exporter_worker_task_error)/sum(worker_exporter_worker_task_number)*100"
    }
   ]
  },
  {
   "title": "worker 任务情况",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "worker_exporter_worker_task_number",
     "legendFormat": "{{job}}任务总数"
    },
    {
     "expr": "worker_exporter_worker_task_error",
     "legendFormat": "{{job}}失败任务数"
    }
   ]
  },
  {
   "title": "Eventlog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {}
   ]
  },
  {
   "title": "状态",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "event_log_exporter_health_status - 0",
     "legendFormat": "status"
    }
   ]
  },
  {
   "title": "scrapes total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "event_log_exporter_scrapes_total"
    }
   ]
  },
  {
   "title": "log count",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "event_log_exporter_container_log_store_log_count",
     "legendFormat": "container log store log count"
    },
    {
     "expr": "event_log_exporter_container_log_store_cache_barrel_count",
     "legendFormat": "container log store cache barrel count"
    },
    {
     "expr": "event_log_exporter_event_store_barrel_count",
     "legendFormat": "event store barrel count"
    },
    {
     "expr": "event_log_exporter_event_store_cache_barrel_count",
     "legendFormat": "event store cache barrel count"
    },
    {
     "expr": "event_log_exporter_event_store_log_count",
     "legendFormat": "event store log count"
    },
    {}
   ]
  },
  {
   "title": "chan cache size",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 96 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "event_log_exporter_chan_cache_size",
     "legendFormat": "{{chan}}"
    }
   ]
  }
 ]
}