{
 "title": "网关",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "近1分钟 请求成功率",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(gateway_requests{status=~\"2..\"}[1m])) / sum(rate(gateway_requests[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "近一分钟 平均延迟",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(gateway_request_duration_seconds_sum[1m])) / avg(rate(gateway_request_duration_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "网关连接数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gateway_connections{state=\"active\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "近1分钟 200 请求数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(gateway_requests{status=\"200\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "近1分钟 404 请求数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(gateway_requests{status=\"404\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top10 访问 Host / 域名",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(increase(gateway_requests[1m])/2) by (host)!=0) ",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Top 10 耗时 Host / 域名",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, max by (host)(irate(gateway_request_duration_seconds_count[5m]))!=0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "网关连接数",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(gateway_connections{state=\"active\"}) by (state,instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "正在读取的网关连接数",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum(gateway_connections{state=\"reading\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "正在等待的网关连接数",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(gateway_connections{state=\"waiting\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "正在写的网关连接数",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum(gateway_connections{state=\"writing\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "请求分布（分钟）",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(gateway_requests[1m])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top10 3XX Host / 域名 （分钟）",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(gateway_requests{status=~\"3..\"}[1m])) by (host) >0/ (sum(rate(gateway_requests[1m])) by (host)>0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top10 4XX Host / 域名 （分钟）",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(gateway_requests{status=~\"4..\"}[1m])) by (host) / (sum(rate(gateway_requests[1m])) by (host)>0))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Top10 5XX Host / 域名 （分钟）",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(gateway_requests{status=~\"5..\"}[1m])) by (host) >0/ (sum(rate(gateway_requests[1m])) by (host)>0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 请求速率 Host / 域名",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(gateway_requests[1m])) by (host)!=0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}