name: push-enterprise-package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Pack offline packages
        env:
          VERSION: ${{ vars.VERSION }}
          DOMESTIC_DOCKER_USERNAME: ${{ vars.DOMESTIC_DOCKER_USERNAME }}
          DOMESTIC_DOCKER_PASSWORD: ${{ vars.DOMESTIC_DOCKER_PASSWORD }}
        run: chmod +x ./enterprise_offline_package.sh && ./enterprise_offline_package.sh
        
      - name: Setup aliyun oss
        uses: manyuanrong/setup-ossutil@master
        with:
          endpoint: oss-cn-shanghai.aliyuncs.com
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          
      - name:  Push to OSS
        run: ossutil cp -rf rainbond-offline-*.tgz oss://rainbond-pkg/offline/5.3-enterprise/
