name: Open-source-version-offline-packaging

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Pack offline packages
        run: chmod +x ./release_offline_package.sh && RBD_VER=v5.3.1-release  ./release_offline_package.sh
        
      - name: Setup aliyun oss
        uses: manyuanrong/setup-ossutil@master
        with:
          endpoint: oss-cn-shanghai.aliyuncs.com
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          
      - name: Push to OSS
        run: ossutil cp -rf rainbond-offline-*.tgz oss://rainbond-pkg/offline/5.3/
