name: build-release-offlice-package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Pack offline packages
        env:
          RBD_VER: v5.4.0-release
        run: chmod +x ./release_offline_package.sh &&  ./release_offline_package.sh
        
      - name: Setup aliyun oss
        uses: manyuanrong/setup-ossutil@master
        with:
          endpoint: oss-cn-shanghai.aliyuncs.com
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          
      - name: Push to OSS
        run: ossutil cp -rf rainbond-offline-*.tgz oss://rainbond-pkg/offline/5.3/
