name: yanxiang-console-V6-amd64
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch'
        required: true
        default: 'yanxiang-new'
      version:
        description: 'version'
        required: true
        default: 'yx-0515'
env:
  DOMESTIC_DOCKER_USERNAME: zhangq@goodrain
  DOMESTIC_DOCKER_PASSWORD: ${{ secrets.DOMESTIC_DOCKER_PASSWORD }}
  DOMESTIC_BASE_NAME: registry.ap-southeast-1.aliyuncs.com
  DOMESTIC_NAMESPACE: goodrain-ee
  GIT_REPO: ${{ secrets.GIT_REPO }}
  
jobs:
  build-ui:
    runs-on: ubuntu-22.04
    steps:
      - name: Build the Docker image
        env:
          BUILD_RBD_APP_UI: false
          ALLINONE: true
          ROUTE_MODE: history
          VERSION: ${{ github.event.inputs.version }}
        run: |
          git clone -b ${{ github.event.inputs.branch }} --depth=1 $GIT_REPO/goodrain/rainbond-ui-cloud.git && cd rainbond-ui-cloud
          chmod +x ./build.sh && ./build.sh
          docker build -f build/Dockerfile.nginx -t registry.ap-southeast-1.aliyuncs.com/goodrain-ee/appstore-user-ui:$VERSION .
          echo "$DOMESTIC_DOCKER_PASSWORD" | docker login -u zhangq@goodrain --password-stdin registry.ap-southeast-1.aliyuncs.com
          docker push registry.ap-southeast-1.aliyuncs.com/goodrain-ee/appstore-user-ui:$VERSION
          docker tag registry.ap-southeast-1.aliyuncs.com/goodrain-ee/appstore-user-ui:$VERSION registry.ap-southeast-1.aliyuncs.com/goodrain-ee/appstore-admin-ui:$VERSION
          docker push registry.ap-southeast-1.aliyuncs.com/goodrain-ee/appstore-admin-ui:$VERSION

  build-allinone:
    runs-on: ubuntu-22.04
    steps:
      - name: Pull code and Build allinone image
        env:
          TRAVIS_PULL_REQUEST: false
          ADAPTOR_BRANCH: enterprise-2023
          VERSION: ${{ github.event.inputs.version }}
        run: |
          git clone -b ${{ github.event.inputs.branch }} --depth=1 $GIT_REPO/goodrain/rainbond-console-cloud.git && cd rainbond-console-cloud
          chmod +x ./release.sh
          ./release.sh allinone
